#!/bin/sh
set -Eeuo pipefail

# kepler = macOS
# luci   = Ubuntu-based Linux

HOSTNAME="$(uname -n)"

install_mac_packages() {
    if ! command -v brew >/dev/null 2>&1; then
        echo "brew not found"
        exit 1
    fi

    brew update

    MAC_PACKAGES="
        gnupg
        pinentry-mac
        go
        lima
        micro
        starship
        stow
    "

    for pkg in $MAC_PACKAGES; do
        brew list --formula "$pkg" >/dev/null 2>&1 || brew install "$pkg"
    done

    MAC_CASK_PACKAGES="
        ghostty
        keepassxc
        transmission
        wireshark-app
        iina
        steam
        vscodium
    "

    for pkg in $MAC_CASK_PACKAGES; do
        brew install --cask  "$pkg" >/dev/null 2>&1 || brew install --cask "$pkg"
    done
}

install_linux_packages() {
    sudo apt-get update

    LINUX_PACKAGES="
        vscodium
        build-essential
        stow
    "

    sudo apt-get install -y $LINUX_PACKAGES
}

apply_mac_dotfiles() {
    stow -t /Users/melonlorrd kepler
    echo "synced dotfiles"
}

apply_linux_dotfiles() {
    stow -t /home/melonlorrd luci
    echo "synced dotfiles"
}

if [ "$HOSTNAME" = "kepler.local" ]; then
    install_mac_packages
    apply_mac_dotfiles
elif [ "$HOSTNAME" = "luci" ]; then
    install_linux_packages
    apply_linux_dotfiles
else
    echo "unknown host"
    exit 1
fi